paths:
  train_csv: /gpfs/data/prostatelab/processed_data/csv/data_split/pj_splits/train_split_April4_testpatient_removed_relabeled.csv
  valid_csv: /gpfs/data/prostatelab/processed_data/csv/data_split/pj_splits/val_split_April4_testpatient_removed_relabeled.csv
  data_dir: /gpfs/data/prostatelab/processed_data/h5/t2_dwi_filtered_20240212
  data_dirs:
    - /gpfs/data/prostatelab/processed_data/h5/t2_dwi_filtered_20240212
  dce_dir: null
  dce_dirs: []
model:
  fusion_type: crossattn
  model: resnet3d
training:
  gpu: True
  epochs: 100
  batch_size: 16
  imbalance_strategy: weighted_loss
  stack_adc_b1500: True
  mode: cspca
data:
  series: ['axt2', 'adc', 'b1500']
  augment: none
  noise_sigma_range: [0.0, 0.0]
  downsample_factors: [1]
  pirads_cutoff: 3
  mask_prostate: False
  normalize: true
  tabular_csv: /gpfs/data/prostatelab/Lakshita/cspca_features_v4.csv
hyperparameters:
  learning_rate: 0.0001
  weight_decay: 0.0
  max_patience: 20
  factor: 0.3
  dropout: 0.2
  optimizer: adam
model_weights:
  save_weights: True
  save_weights_dir: /gpfs/data/prostatelab/Lakshita/experiments/fusion_multihead_v2
  load_weights: True
  model_ckpt: /gpfs/data/prostatelab/Lakshita/experiments/cspca/epoch=02_AUC_best_val_pirads_auc=0.84_axt2_adc_b1500_baseline_cspca_pirads_cutoff_3.ckpt
  disable_gradient: False
logging:
  log_run: False
  project_name: lakshita_multimodal
  run_name: resnet3d_multihead_v2
  plot_roc: False
  plot_confusion_matrix: False
  plot_pirads_breakdown: False
debugging:
  debug: False
  preds_dir: /gpfs/data/prostatelab/Lakshita/experiments/fusion_multihead_v2
  max_test_volumes: -1
  compute_gradcam: False